name: Build macOS App

on:
  push:
    tags:
      - 'v*'  # 当你发布 tag，例如 v1.0.0 时自动打包

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install py2app

      - name: Build macOS App
        run: python3 setup.py py2app

      - name: Compress App
        run: |
          cd dist
          zip -r YahooFinanceExporter.zip YahooFinanceExporter.app

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: dist/YahooFinanceExporter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
