name: Build macOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pyinstaller
          pip3 install chardet

      - name: Build macOS Executable
        run: |
          pyinstaller --onefile fetch_yahoo_finance_data.py

      - name: Clean everything except the binary
        run: |
          find . -maxdepth 1 ! -name 'dist' ! -name '.' -exec rm -rf {} +
          cd dist
          zip -r YahooFinanceExporter.zip *

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/YahooFinanceExporter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
